name: CI
on: 
  - push
  - workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          # Version is duplicated in the .gitpod.Dockerfile
          deno-version: v1.20.3

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CI
        run: |
          make ci
