name: CI
on:
  - push
  - workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          # Version is duplicated in the .gitpod.Dockerfile
          deno-version: v1.20.3

      - name: Run CI
        run: |
          make ci
        env:
          #CI as of right now doesn't exercise the aws sdk fork
          #So setting this so it doesn't throw an error here - https://github.com/christophgysin/aws-sdk-js-v3/blob/deno/deno/config-resolver/regionConfig/resolveRegionConfig.ts#L23
          AWS_DEFAULT_REGION: "unused"
